=== aayushlabs/web_labs_2-/q26/aayush_04_q26.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="author" type="xs:string"/>
                            <xs:element name="price" type="xs:decimal"/>
                            <xs:element name="year" type="xs:integer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== aayushlabs/web_labs_2-/q26/aayush_04_q26.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="aayush_04_q26.xsd">

    <book>
        <title>The Alchemist</title>
        <author>Paulo Coelho</author>
        <price>450.00</price>
        <year>1988</year>
    </book>

    <book>
        <title>Atomic Habits</title>
        <author>James Clear</author>
        <price>650.00</price>
        <year>2018</year>
    </book>

</books>
